<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-81b5c3e63835cfde897ecd3d35a35a41.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.3">

  <meta name="author" content="Léo Belzile">
  <title>Bayesian modelling</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
    /* CSS for citations */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
      margin-bottom: 0em;
    }
    .hanging-indent div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-da069d641d4916e8549bf8dc2b95f825.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-color="#ff585d" class="quarto-title-block center">
  <h1 class="title">Bayesian modelling</h1>
  <p class="subtitle">Priors</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Léo Belzile 
</div>
</div>
</div>

  <p class="date">Last compiled Tuesday Apr 1, 2025</p>
</section>
<section id="priors" class="slide level2">
<h2>Priors</h2>
<p>The posterior density is</p>
<p><span class="math display">\[\begin{align*}
\color{#D55E00}{p(\boldsymbol{\theta} \mid \boldsymbol{Y})} = \frac{\color{#0072B2}{p(\boldsymbol{Y} \mid \boldsymbol{\theta})} \times  \color{#56B4E9}{p(\boldsymbol{\theta})}}{\color{#E69F00}{\int p(\boldsymbol{Y} \mid \boldsymbol{\theta}) p(\boldsymbol{\theta})\mathrm{d} \boldsymbol{\theta}}},
\end{align*}\]</span></p>
<p>where <span class="math display">\[\color{#D55E00}{\text{posterior}} \propto \color{#0072B2}{\text{likelihood}} \times \color{#56B4E9}{\text{prior}}\]</span></p>
<p>We need to determine a suitable prior.</p>
</section>
<section id="impact-of-the-prior" class="slide level2">
<h2>Impact of the prior</h2>
<p>The posterior is a compromise prior and likelihood:</p>
<ul>
<li>the more informative the prior, the more the posterior resembles it.</li>
<li>in large samples, the effect of the prior is often negligible</li>
</ul>
</section>
<section id="controversial" class="slide level2">
<h2>Controversial?</h2>
<ul>
<li>No unique choice for the prior: different analysts get different inferences</li>
<li>What is the robustness to the prior specification? Check through sensitivity analysis.</li>
<li>Even with prior knowledge, hard to elicit parameter (many different models could yield similar summary statistics)</li>
</ul>
</section>
<section id="choosing-priors" class="slide level2">
<h2>Choosing priors</h2>
<p>Infinite number of choice, but many default choices…</p>
<ul>
<li>conditionally conjugate priors (ease of interpretation, computational advantages)</li>
<li>flat priors and vague priors (mostly uninformative)</li>
<li>informative priors (expert opinion)</li>
<li>Jeffrey’s priors (improper, invariant to reparametrization)</li>
<li>penalized complexity (regularization)</li>
<li>shrinkage priors (variable selection, reduce overfitting)</li>
</ul>
</section>
<section id="determining-hyperparameters" class="slide level2">
<h2>Determining hyperparameters</h2>
<p>We term <strong>hyperparameters</strong> the parameters of the (hyper)priors.</p>
<p>How to elicit reasonable values for them?</p>
<ul>
<li>use moment matching to get sensible values</li>
<li>trial-and-error using the prior predictive
<ul>
<li>draw a parameter value from the prior <span class="math inline">\(\boldsymbol{\theta}_0\)</span></li>
<li>for each, generate a new observation from the model <span class="math inline">\(f(y_{\text{new}} \mid \boldsymbol{\theta}_0)\)</span></li>
</ul></li>
</ul>
</section>
<section id="example-of-simple-linear-regression" class="slide level2">
<h2>Example of simple linear regression</h2>
<p>Working with standardized response and inputs <span class="math display">\[x_i \mapsto (x_i - \overline{x})/\mathrm{sd}(\boldsymbol{x}),\]</span></p>
<ul>
<li>the slope is the correlation between explanatory <span class="math inline">\(\mathrm{X}\)</span> and response <span class="math inline">\(Y\)</span></li>
<li>the intercept should be mean zero</li>
<li>are there sensible bounds for the range of the response?</li>
</ul>
</section>
<section id="example---simple-linear-regression" class="slide level2">
<h2>Example - simple linear regression</h2>
<p>Consider the relationship between height (<span class="math inline">\(Y,\)</span> in cm) and weight (<span class="math inline">\(X,\)</span> in kg) among humans adults.<sup>1</sup></p>
<p>Model using a simple linear regression</p>
<p><span class="math display">\[\begin{align*}
Y_i &amp;\sim \mathsf{Gauss}(\mu_i, \sigma^2) \\
\mu_i &amp;= \beta_0 + \beta_1(\mathrm{x}_i - \overline{x}) \\
\beta_0 &amp;\sim \mathsf{Gauss}(178, 20^2) \\
\sigma &amp;\sim \mathsf{unif}(0, 50)
\end{align*}\]</span> What about the slope parameter prior <span class="math inline">\(p(\beta_1)\)</span>?</p>
<aside><ol class="aside-footnotes"><li id="fn1"><p>Section 4.4.1 of <span class="citation" data-cites="McElreath:2020">McElreath (<a href="#/references" role="doc-biblioref" onclick="">2020</a>)</span></p></li></ol></aside></section>
<section id="priors-for-the-slope" class="slide level2 smaller">
<h2>Priors for the slope</h2>

<img data-src="bayesmod-slides3_files/figure-revealjs/fig-priors-draw-height-weight-1.png" width="960" class="r-stretch quarto-figure-center" id="fig-priors-draw-height-weight"><p class="caption">
Figure&nbsp;1: Prior draws of linear regressions with different priors: vague <span class="math inline">\(\beta_1 \sim \mathsf{Gauss}(0, 100)\)</span> (left) and lognormal <span class="math inline">\(\ln(\beta_1) \sim \mathsf{Gauss}(0,1)\)</span> (right). Figure 4.5 of <span class="citation" data-cites="McElreath:2020">McElreath (<a href="#/references" role="doc-biblioref" onclick="">2020</a>)</span>. The Guiness record for the world’s tallest person is 272cm.
</p></section>
<section id="conjugate-priors" class="slide level2">
<h2>Conjugate priors</h2>
<p>A prior density <span class="math inline">\(p(\boldsymbol{\theta})\)</span> is conjugate for likelihood <span class="math inline">\(L(\boldsymbol{\theta}; \boldsymbol{y})\)</span> if the product <span class="math inline">\(L(\boldsymbol{\theta}; \boldsymbol{y})p(\boldsymbol{\theta}),\)</span> after renormalization, is of the same parametric family as the prior.</p>
<p>Distributions that are exponential family admit conjugate priors.</p>
<div style="font-size: 65%;">
<p>A distribution is an exponential family if it’s density can be written <span class="math display">\[\begin{align*}
f(y; \boldsymbol{\theta}) = \exp\left\{ \sum_{k=1}^K Q_k(\boldsymbol{\theta}) t_k(y) + D(\boldsymbol{\theta}) + h(y)\right\}.
\end{align*}\]</span> The support of <span class="math inline">\(f\)</span> must not depend on <span class="math inline">\(\boldsymbol{\theta}.\)</span></p>
</div>
</section>
<section id="conjugate-priors-for-common-exponential-families" class="slide level2 smaller">
<h2>Conjugate priors for common exponential families</h2>
<table class="caption-top">
<colgroup>
<col style="width: 34%">
<col style="width: 32%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th>distribution</th>
<th style="text-align: left;">unknown parameter</th>
<th style="text-align: left;">conjugate prior</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(Y \sim \mathsf{expo}(\lambda)\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\lambda\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\lambda \sim \mathsf{gamma}(\alpha, \beta)\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(Y \sim \mathsf{Poisson}(\mu)\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\mu\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\mu \sim \mathsf{gamma}(\alpha, \beta)\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(Y \sim \mathsf{binom}(n, \theta)\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\theta\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\theta \sim \mathsf{Be}(\alpha, \beta)\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(Y \sim \mathsf{Gauss}(\mu, \sigma^2)\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\mu\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\mu \sim \mathsf{Gauss}(\nu, \omega^2)\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(Y \sim \mathsf{Gauss}(\mu, \sigma^2)\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\sigma\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\sigma^{-2} \sim \mathsf{gamma}(\alpha, \beta)\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(Y \sim \mathsf{Gauss}(\mu, \sigma^2)\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\mu, \sigma\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\mu \mid \sigma^2 \sim \mathsf{Gauss}(\nu, \omega \sigma^2),\)</span> <span class="math inline">\(\sigma^{-2} \sim \mathsf{gamma}(\alpha, \beta)\)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="conjugate-prior-for-the-poisson" class="slide level2">
<h2>Conjugate prior for the Poisson</h2>
<p>If <span class="math inline">\(Y \sim \mathsf{Poisson}(\mu)\)</span> with density <span class="math inline">\(f(y) = \mu^x\exp(-\mu x)/x!,\)</span> then for <span class="math inline">\(\mu \sim \mathsf{gamma}(\alpha, \beta)\)</span> with <span class="math inline">\(\alpha, \beta\)</span> fixed. Consider an i.i.d. sample with mean <span class="math inline">\(\overline{y}.\)</span> The posterior density is</p>
<p><span class="math display">\[
p(\mu \mid y) \stackrel{\mu}{\propto} \mu^{n\overline{y}} \exp\left(-\mu n\overline{y}\right) \mu^{\alpha-1} \exp(-\beta \mu)
\]</span> so must be gamma <span class="math inline">\(\mathsf{gamma}(n\overline{y} + \alpha, n\overline{y} + \beta).\)</span></p>
<p><em>Parameter interpretation</em>: <span class="math inline">\(\alpha\)</span> events in <span class="math inline">\(\beta\)</span> time intervals.</p>
</section>
<section id="conjugate-prior-for-gaussian-known-variance" class="slide level2 smaller">
<h2>Conjugate prior for Gaussian (known variance)</h2>
<p>Consider an iid sample, <span class="math inline">\(Y_i \sim \mathsf{Gauss}(\mu, \sigma^2)\)</span> and let <span class="math inline">\(\mu \mid \sigma \sim \mathsf{Gauss}(\nu, \sigma^2\tau^2).\)</span> Then, <span class="math display">\[\begin{align*}
p(\mu, \sigma) &amp;\propto \frac{p(\sigma)}{\sigma^{n+1}} \exp\left\{ -\frac{1}{2\sigma^2}\sum_{i=1}^n (y_{i}-\mu)^2\right\} \exp\left\{-\frac{1}{2\sigma^2\tau^2}(\mu - \nu)^2\right\}
\\&amp;\propto \frac{p(\sigma)}{\sigma^{n+1}} \exp\left\{\left(\sum_{i=1}^n y_{i} + \frac{\nu}{\tau^2}\right)\frac{\mu}{\sigma^2} - \left( \frac{n}{2} +\frac{1}{2\tau^2}\right)\frac{\mu^2}{\sigma^2}\right\}.
\end{align*}\]</span></p>
<p>The conditional posterior <span class="math inline">\(p(\mu \mid \sigma)\)</span> is Gaussian with</p>
<ul>
<li>mean <span class="math inline">\((n\overline{y}\tau^2 + \nu)/(n\tau^2 + 1)\)</span> and</li>
<li>precision (reciprocal variance) <span class="math inline">\((n + 1/\tau^2)/\sigma^2.\)</span></li>
</ul>
</section>
<section id="upworthy-examples" class="slide level2">
<h2>Upworthy examples</h2>
<ul>
<li>The Upworthy Research Archive <span class="citation" data-cites="Matias:2021">(<a href="#/references" role="doc-biblioref" onclick="">Matias et al., 2021</a>)</span> contains results for 22743 experiments, with a click through rate of 1.58% on average and a standard deviation of 1.23%.</li>
<li>We consider an A/B test that compared four different headlines for a story.</li>
<li>We model the conversion <strong>rate</strong> for each using <span class="math inline">\(\texttt{click}_i \sim \mathsf{Poisson}(\lambda_i\texttt{impression}_i).\)</span></li>
</ul>
<p>We treat <span class="math inline">\(\texttt{impression}\)</span> as a known offset.</p>
</section>
<section id="headlines" class="slide level2">
<h2>Headlines</h2>
<p>Consider an A/B test from November 23st, 2014, that compared four different headlines for a story on Sesame Street workshop with interviews of children whose parents were in jail and visiting them in prisons. The headlines tested were:</p>
<ol type="1">
<li class="fragment">Some Don’t Like It When He Sees His Mom. But To Him? Pure Joy. Why Keep Her From Him?</li>
<li class="fragment">They’re Not In Danger. They’re Right. See True Compassion From The Children Of The Incarcerated.</li>
<li class="fragment">Kids Have No Place In Jail … But In This Case, They <em>Totally</em> Deserve It.</li>
<li class="fragment">Going To Jail <em>Should</em> Be The Worst Part Of Their Life. It’s So Not. Not At All.</li>
</ol>
</section>
<section id="ab-test-sesame-street-example" class="slide level2">
<h2>A/B test: Sesame street example</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">headline</th>
<th style="text-align: right;">impressions</th>
<th style="text-align: right;">clicks</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">H1</td>
<td style="text-align: right;">3060</td>
<td style="text-align: right;">49</td>
</tr>
<tr class="even">
<td style="text-align: left;">H2</td>
<td style="text-align: right;">2982</td>
<td style="text-align: right;">20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H3</td>
<td style="text-align: right;">3112</td>
<td style="text-align: right;">31</td>
</tr>
<tr class="even">
<td style="text-align: left;">H4</td>
<td style="text-align: right;">3083</td>
<td style="text-align: right;">9</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="moment-matching-for-gamma-distribution" class="slide level2">
<h2>Moment matching for gamma distribution</h2>
<p>For <span class="math inline">\(Y \sim \mathsf{gamma}(\alpha, \beta)\)</span> with <span class="math inline">\(\beta\)</span> the rate parameter, we have <span class="math display">\[\begin{align*}
\mathsf{E}(Y)=\alpha/\beta, \qquad \mathsf{Va}(Y)=\alpha/\beta^2.
\end{align*}\]</span> We can solve for <span class="math inline">\(\beta =\mathsf{E}_0(\lambda)/\mathsf{Va}_0(\lambda)\)</span> and then use the mean relationship to retrieve $.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a>mu <span class="ot">&lt;-</span> <span class="fl">0.0158</span>; sd <span class="ot">&lt;-</span> <span class="fl">0.0123</span></span>
<span id="cb1-2"><a></a>(beta <span class="ot">&lt;-</span> mu<span class="sc">/</span>sd<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 104.4352</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a>(alpha <span class="ot">&lt;-</span> mu <span class="sc">*</span> beta)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.650076</code></pre>
</div>
</div>
<p>Moment matching gives <span class="math inline">\(\alpha = 1.65\)</span> and <span class="math inline">\(\beta = 104.44.\)</span></p>
</section>
<section id="posterior-distributions-for-sesame-street" class="slide level2">
<h2>Posterior distributions for Sesame Street</h2>

<img data-src="bayesmod-slides3_files/figure-revealjs/fig-upworthy-1.png" width="768" class="r-stretch quarto-figure-center" id="fig-upworthy"><p class="caption">
Figure&nbsp;2: Gamma posteriors of the conversion rate for the Upworthy Sesame street headline.
</p></section>
<section id="proper-priors" class="slide level2">
<h2>Proper priors</h2>
<div id="thm-proper-priors" class="theorem">
<p><span class="theorem-title"><strong>Theorem 1</strong></span> A sufficient condition for a prior to yield a proper (i.e., integrable) posterior density function is that it is (proportional) to a density function.</p>
</div>
<ul>
<li>If we pick an improper prior, we need to check that the posterior is well-defined.</li>
<li>The answer to this question may depend on the sample size.</li>
</ul>
</section>
<section id="proper-posterior-in-a-random-effect-model" class="slide level2">
<h2>Proper posterior in a random effect model</h2>
<p>Consider a Gaussian random effect model with <span class="math inline">\(n\)</span> independent observations in <span class="math inline">\(J\)</span> groups</p>
<p>The <span class="math inline">\(i\)</span>th observation in group <span class="math inline">\(j\)</span> is <span class="math display">\[\begin{align*}
Y_{ij} &amp;\sim \mathsf{Gauss}(\mu_{ij}, \sigma^2) \\
\mu_{ij}&amp;= \mathbf{X}_i \boldsymbol{\beta} + \alpha_j,  \\
\alpha_j &amp;\sim \mathsf{Gauss}(0, \tau^2)\\
...
\end{align*}\]</span></p>
</section>
<section id="conditions-for-a-proper-posterior" class="slide level2">
<h2>Conditions for a proper posterior</h2>
<ul>
<li>for <span class="math inline">\(\tau \sim \mathsf{unif}(0, \infty),\)</span> we need at least <span class="math inline">\(J \geq 3\)</span> ‘groups’ for the posterior to be proper.</li>
<li>if we take <span class="math inline">\(p(\tau) \propto \tau^{-1},\)</span> the posterior is never proper.</li>
</ul>
<p>As <span class="citation" data-cites="Gelman:2006">Gelman (<a href="#/references" role="doc-biblioref" onclick="">2006</a>)</span> states:</p>
<blockquote>
<p>in a hierarchical model the data can never rule out a group-level variance of zero, and so [a] prior distribution cannot put an infinite mass in this area</p>
</blockquote>
</section>
<section id="improper-priors-as-limiting-cases" class="slide level2">
<h2>Improper priors as limiting cases</h2>
<p>We can view the improper prior as a limiting case <span class="math display">\[\sigma \sim \mathsf{unif}(0, t), \qquad t \to \infty.\]</span></p>
<p>The Haldane prior for <span class="math inline">\(\theta\)</span> in a binomial model is <span class="math inline">\(\theta^{-1}(1-\theta)^{-1},\)</span> a limiting <span class="math inline">\(\mathsf{Be}(0,0)\)</span> distribution.</p>
<p>The improper prior <span class="math inline">\(p(\sigma) \propto \sigma^{-1}\)</span> is equivalent to an inverse gamma <span class="math inline">\(\mathsf{inv. gamma}(\epsilon, \epsilon)\)</span> when <span class="math inline">\(\epsilon \to 0.\)</span></p>
<p>The limiting posterior is thus improper for random effects scales, so the value of <span class="math inline">\(\epsilon\)</span> matters.</p>
</section>
<section id="mdi-prior-for-generalized-pareto" class="slide level2">
<h2>MDI prior for generalized Pareto</h2>
<p>Let <span class="math inline">\(Y_i \sim \mathsf{GP}(\sigma, \xi)\)</span> be generalized Pareto with density <span class="math display">\[f(x) = \sigma^{-1}(1+\xi x/\sigma)_{+}^{-1/\xi-1}\]</span> for <span class="math inline">\(\sigma&gt;0\)</span> and <span class="math inline">\(\xi \in \mathbb{R},\)</span> and <span class="math inline">\(x_{+} =\max\{0, x\}.\)</span></p>
<p>Consider the maximum data information (MDI) <span class="math display">\[p(\xi) \propto \exp(-\xi).\]</span></p>
<p>Since <span class="math inline">\(\lim_{\xi \to -\infty} \exp(-\xi) = \infty,\)</span> the prior density increases without bound as <span class="math inline">\(\xi\)</span> becomes smaller.</p>
</section>
<section id="truncated-mdi-for-generalized-pareto-distribution" class="slide level2">
<h2>Truncated MDI for generalized Pareto distribution</h2>
<p>The MDI prior leads to an improper posterior without modification.</p>

<img data-src="bayesmod-slides3_files/figure-revealjs/fig-mdiprior-1.png" style="width:100.0%" class="r-stretch quarto-figure-center" id="fig-mdiprior"><p class="caption">
Figure&nbsp;3: Unscaled maximum data information (MDI) prior density.
</p><p>If we restrict the range of the MDI prior <span class="math inline">\(p(\xi)\)</span> to <span class="math inline">\(\xi \geq -1,\)</span> then <span class="math inline">\(p(\xi + 1) \sim \mathsf{expo}(1)\)</span> and posterior is proper.</p>
</section>
<section id="flat-priors" class="slide level2">
<h2>Flat priors</h2>
<p>Uniform prior over the support of <span class="math inline">\(\theta,\)</span> <span class="math display">\[p(\theta) \propto 1.\]</span></p>
<p>Improper prior unless <span class="math inline">\(\theta \in [a,b]\)</span> for finite <span class="math inline">\(a, b.\)</span></p>
</section>
<section id="flat-priors-for-scale-parameters" class="slide level2">
<h2>Flat priors for scale parameters</h2>
<p>Consider a scale parameter <span class="math inline">\(\sigma &gt; 0.\)</span></p>
<ul>
<li>We could truncate the range, e.g., <span class="math inline">\(\sigma \sim \mathsf{unif}(0, 50),\)</span> but this is not ‘uninformative’, as extreme values of <span class="math inline">\(\sigma\)</span> are as likely as small ones.</li>
<li>These priors are not invariant: if <span class="math inline">\(p\{\log(\sigma)\} \propto 1\)</span> implies <span class="math inline">\(p(\sigma) \propto \sigma^{-1}\)</span> so can be informative on another scale.</li>
</ul>
</section>
<section id="vague-priors" class="slide level2">
<h2>Vague priors</h2>
<p>Vague priors are very diffuse proper prior.</p>
<p>For example, a vague Gaussian prior for regression coefficients on standardized data, <span class="math display">\[\boldsymbol{\beta} \sim \mathsf{Gauss}_p(\mathbf{0}_p, 100\mathbf{I}_p).\]</span></p>
<ul>
<li>if we consider a logistic regression with a binary variable <span class="math inline">\(\mathrm{X}_j \in \{0,1\},\)</span> then <span class="math inline">\(\beta_j =5\)</span> gives odds ratios of 150, and <span class="math inline">\(\beta_j=10\)</span> of around 22K…</li>
</ul>
</section>
<section id="invariance-and-jeffreys-prior" class="slide level2">
<h2>Invariance and Jeffrey’s prior</h2>
<p>In single-parameter models, the <strong>Jeffrey’s prior</strong> <span class="math display">\[p(\theta) \propto |\imath(\theta)|^{1/2},\]</span> proportional to the square root of the determinant of the Fisher information matrix, is invariant to any (differentiable) reparametrization.</p>
</section>
<section id="jeffreys-prior-for-the-binomial-distribution" class="slide level2">
<h2>Jeffrey’s prior for the binomial distribution</h2>
<p>Consider <span class="math inline">\(Y \sim \mathsf{binom}(1, \theta).\)</span> The negative of the second derivative of the log likelihood with respect to <span class="math inline">\(p\)</span> is <span class="math display">\[
\jmath(\theta) = - \partial^2 \ell(\theta; y) / \partial \theta^2 = y/\theta^2 + (1-y)/(1-\theta)^2.
\]</span></p>
<p>Since <span class="math inline">\(\mathsf{E}(Y)=\theta,\)</span> the Fisher information is <span class="math display">\[\imath(\vartheta) = \mathsf{E}\{\jmath(\theta)\}=1/\theta + 1/(1-\theta) = 1/\{\theta(1-\theta)\}.\]</span> Jeffrey’s prior is therefore <span class="math inline">\(p(\theta) \propto \theta^{-1/2}(1-\theta)^{-1/2},\)</span> a conjugate Beta prior <span class="math inline">\(\mathsf{Be}(0.5,0.5).\)</span></p>
</section>
<section id="invariant-priors-for-location-scale-families" class="slide level2">
<h2>Invariant priors for location-scale families</h2>
<p>For a location-scale family with location <span class="math inline">\(\mu\)</span> and scale <span class="math inline">\(\sigma,\)</span> the independent priors <span class="math display">\[\begin{align*}
p(\mu) &amp;\propto 1\\
p(\sigma) &amp;\propto \sigma^{-1}
\end{align*}\]</span> are location-scale invariant.</p>
<p>The results are invariant to affine transformations of the units, <span class="math inline">\(\vartheta = a + b \theta.\)</span></p>
</section>
<section id="penalized-complexity-priors" class="slide level2">
<h2>Penalized complexity priors</h2>
<p><span class="citation" data-cites="Simpson:2017">Simpson et al. (<a href="#/references" role="doc-biblioref" onclick="">2017</a>)</span> consider a principled way of constructing priors that penalized model complexity for stable inference and limit over-specification.</p>
<p>Computes Kullback–Leibler divergence between <span class="math inline">\(f\)</span> and base model <span class="math inline">\(f_0\)</span> densities, builds an exponential prior on the distance scale and backtransform.</p>
<p>The resulting prior is scale-invariant, but it’s derivation is nontrivial.</p>
</section>
<section id="penalized-complexity-prior-for-random-effect-scale" class="slide level2">
<h2>Penalized complexity prior for random effect scale</h2>
<p>If <span class="math inline">\(\alpha_j \sim \mathsf{Gauss}(0, \zeta^2),\)</span> the penalized complexity prior for the scale <span class="math inline">\(\zeta \sim \mathsf{expo}(\lambda).\)</span></p>
<p>Elicit <span class="math inline">\(Q,\)</span> a high quantile of the standard deviation <span class="math inline">\(\zeta\)</span> with tail probability <span class="math inline">\(\alpha\)</span> and set <span class="math inline">\(\lambda = -\log(\alpha/Q).\)</span></p>
</section>
<section id="priors-for-scale-of-random-effects" class="slide level2">
<h2>Priors for scale of random effects</h2>
<p>The conjugate inverse gamma prior <span class="math inline">\(p(\zeta^2) \sim \mathsf{inv. gamma}(\alpha, \beta)\)</span> is such that the mode for <span class="math inline">\(\zeta^2\)</span> is <span class="math inline">\(\beta/(1+\alpha).\)</span></p>
<p>Often, we take <span class="math inline">\(\beta=\alpha = 0.01\)</span> or <span class="math inline">\(0.001,\)</span> but this leads to near-improper priors, so small values of the parameters are not optimal for ‘random effects’.</p>
<p>The inverse gamma prior cannot provide shrinkage or allow for no variability between groups.</p>
</section>
<section id="priors-for-scale-of-random-effects-1" class="slide level2">
<h2>Priors for scale of random effects</h2>
<p>A popular suggestion, due to <span class="citation" data-cites="Gelman:2006">Gelman (<a href="#/references" role="doc-biblioref" onclick="">2006</a>)</span>, is to take a centered Student-<span class="math inline">\(t\)</span> distribution with <span class="math inline">\(\nu\)</span> degrees of freedoms, truncated over <span class="math inline">\([0, \infty)\)</span> with scale <span class="math inline">\(s.\)</span></p>
<ul>
<li>since the mode is at zero, provides support for the base model</li>
<li>we want small degrees of freedom <span class="math inline">\(\nu,\)</span> preferable to take <span class="math inline">\(\nu=3\)</span>? Cauchy model (<span class="math inline">\(\nu=1\)</span>) still popular.</li>
</ul>
</section>
<section id="prior-sensitivity" class="slide level2">
<h2>Prior sensitivity</h2>
<p>Does the priors matter? As robustness check, one can fit the model with</p>
<ul>
<li>different priors function</li>
<li>different hyperparameter values</li>
</ul>
<p>Costly, but may be needed to convince reviewers ;)</p>
</section>
<section id="distraction-from-smartwach" class="slide level2">
<h2>Distraction from smartwach</h2>
<p>We consider an experimental study conducted at Tech3Lab on road safety.</p>
<ul>
<li>In <span class="citation" data-cites="Brodeur:2021">Brodeur et al. (<a href="#/references" role="doc-biblioref" onclick="">2021</a>)</span>, 31 participants were asked to drive in a virtual environment.</li>
<li>The number of road violation was measured for 4 different type of distractions (phone notification, phone on speaker, texting and smartwatch).</li>
<li>Balanced data, random order of tasks</li>
</ul>
</section>
<section id="poisson-mixed-model" class="slide level2">
<h2>Poisson mixed model</h2>
<p>We model the number of violations, <code>nviolation</code> as a function of distraction type (<code>task</code>) and participant <code>id</code>. <span class="math display">\[\begin{align*}
\texttt{nviolation}_{ij} &amp;\sim \mathsf{Poisson}(\mu_{ij})\\
\mu_{ij} &amp;= \exp(\beta_{j} + \alpha_i),\\
\beta_j &amp;\sim \mathsf{Gauss}(0, 100), \\
\alpha_i &amp;\sim \mathsf{Gauss}(0, \tau^2).
\end{align*}\]</span></p>
<p>Specifically,</p>
<ul>
<li><span class="math inline">\(\beta_j\)</span> is the coefficient for <code>task</code> <span class="math inline">\(j\)</span> (distraction type),</li>
<li><span class="math inline">\(\alpha_i\)</span> is the random effect of participant <span class="math inline">\(i.\)</span></li>
</ul>
</section>
<section id="priors-for-random-effect-scale" class="slide level2">
<h2>Priors for random effect scale</h2>
<p>Consider different priors for <span class="math inline">\(\tau\)</span></p>
<ul>
<li>flat uniform prior <span class="math inline">\(\mathsf{unif}(0,10)\)</span></li>
<li>conjugate inverse gamma <span class="math inline">\(\mathsf{inv. gamma}(0.01, 0.01)\)</span> prior</li>
<li>a truncated Student-<span class="math inline">\(t\)</span> on <span class="math inline">\([0, \infty)\)</span> with <span class="math inline">\(\nu=3\)</span> degrees of freedom, <span class="math inline">\(\mathsf{Student}_{+}(0,1,3)\)</span></li>
<li>a penalized complexity prior such that the 0.95 percentile of the scale is 5, corresponding to <span class="math inline">\(\mathsf{expo}(0.6).\)</span></li>
</ul>
</section>
<section id="sensitivity-analysis-for-smartwatch-data" class="slide level2">
<h2>Sensitivity analysis for smartwatch data</h2>

<img data-src="fig/fig-sensitivity.png" width="672" class="r-stretch quarto-figure-center" id="fig-posterior-tau"><p class="caption">
Figure&nbsp;4: Posterior density of <span class="math inline">\(\tau\)</span> for four different priors. The circle denotes the median and the bars the 50% and 95% percentile credible intervals.
</p><p>Basically indistinguishable results for the random scale..</p>
</section>
<section id="eight-schools-example" class="slide level2">
<h2>Eight schools example</h2>
<p>Average results on SAT program, for eight schools <span class="citation" data-cites="Rubin:1981">(<a href="#/references" role="doc-biblioref" onclick="">Rubin, 1981</a>)</span>.</p>
<p>The hierarchical model is</p>
<p><span class="math display">\[\begin{align*}
Y_i &amp;\sim \mathsf{Gauss}(\mu + \eta_i, \sigma_i^2)\\
\mu &amp;\sim \mathsf{Gauss}(0, 100)\\
\eta_i &amp; \sim \mathsf{Gauss}(0, \tau^2)
\end{align*}\]</span> Given the large sample in each school, we treat <span class="math inline">\(\sigma_i\)</span> as fixed data by using the sample standard deviation.</p>
</section>
<section id="sensibility-analysis-for-eight-schools-example" class="slide level2">
<h2>Sensibility analysis for eight schools example</h2>

<img data-src="fig/eightschools-stddev-raneff.png" width="600" class="r-stretch quarto-figure-center" id="fig-posterior-eightschool"><p class="caption">
Figure&nbsp;5: Posterior density of the school-specific random effects standard deviation <span class="math inline">\(\tau\)</span> under different priors.
</p></section>
<section id="references" class="slide level2 smaller scrollable">
<h2>References</h2>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-Brodeur:2021" class="csl-entry" role="listitem">
Brodeur, M., Ruer, P., Léger, P.-M., &amp; Sénécal, S. (2021). Smartwatches are more distracting than mobile phones while driving: Results from an experimental study. <em>Accident Analysis &amp; Prevention</em>, <em>149</em>, 105846. <a href="https://doi.org/10.1016/j.aap.2020.105846">https://doi.org/10.1016/j.aap.2020.105846</a>
</div>
<div id="ref-Gelman:2006" class="csl-entry" role="listitem">
Gelman, A. (2006). Prior distributions for variance parameters in hierarchical models (comment on article by <span>B</span>rowne and <span>D</span>raper). <em>Bayesian Analysis</em>, <em>1</em>(3), 515–534. <a href="https://doi.org/10.1214/06-ba117a">https://doi.org/10.1214/06-ba117a</a>
</div>
<div id="ref-Matias:2021" class="csl-entry" role="listitem">
Matias, J. N., Munger, K., Le Quere, M. A., &amp; Ebersole, C. (2021). The <span>U</span>pworthy <span>R</span>esearch <span>A</span>rchive, a time series of 32,487 experiments in <span>U.S.</span> media. <em>Scientific Data</em>, <em>8</em>(195). <a href="https://doi.org/10.1038/s41597-021-00934-7">https://doi.org/10.1038/s41597-021-00934-7</a>
</div>
<div id="ref-McElreath:2020" class="csl-entry" role="listitem">
McElreath, R. (2020). <em>Statistical rethinking: A <span>B</span>ayesian course with examples in <span>R</span> and <span>STAN</span></em> (2nd ed.). Chapman; Hall/CRC.
</div>
<div id="ref-Rubin:1981" class="csl-entry" role="listitem">
Rubin, D. B. (1981). Estimation in parallel randomized experiments. <em>Journal of Educational Statistics</em>, <em>6</em>(4), 377–401. <a href="https://doi.org/10.3102/10769986006004377">https://doi.org/10.3102/10769986006004377</a>
</div>
<div id="ref-Simpson:2017" class="csl-entry" role="listitem">
Simpson, D., Rue, H., Riebler, A., Martins, T. G., &amp; Sørbye, S. H. (2017). Penalising model component complexity: A principled, practical approach to constructing priors. <em>Statistical Science</em>, <em>32</em>(1), 1–28. <a href="https://doi.org/10.1214/16-sts576">https://doi.org/10.1214/16-sts576</a>
</div>
</div>
</section>

    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="fig/logo_hec_montreal_bleu_web.png" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1200,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp("https:\/\/lbelzile\.github\.io\/bayesmod");
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>