project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
  resources:
    - "files/"
    - "projects/"
    - "slides/*.html"
    - "slides/*.pdf"
    - "slides/img/"
    - "slides/libs/"
    - "slides/css/"
    - "slides/*_files/"

# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes

bibliography: files/bib/references.bib
csl: files/bib/apa.csl

website:
  title: "Bayesian modelling"
  site-url: "https://lbelzile.github.io/bayesmod"
  description: "Hands on introduction to Bayesian data analysis. The course will cover the formulation, evaluation and comparison of Bayesian models through examples."

  navbar:
    pinned: true
    background: "#ff585d"
    right:
      - syllabus.qmd
#      - schedule.qmd
      - text: "Content"
        file: content/index.qmd
      - text: "Exercises"
        file: exercises/index.qmd
      - text: "News"
        file: news/index.qmd
      - text: "Notes"
        href: "https://lbelzile.github.io/MATH80601A/"
 #     - icon: box
 #       href: "https://lbelzile.github.io/hecbayesmod"
 #       aria-label: Datasets

  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      foreground: "#000000"
      contents:
        - section: "Overview"
          contents:
            - content/index.qmd
        - section: "Installation"
          contents:
            - text: "**R** and RStudio"
              file: example/installation.qmd    
        - section: "Course content"
          contents:
            - text: "1: Introduction"
              file: content/01-content.qmd
            - text: "2: Bayesics"
              file: content/02-content.qmd
            - text: "3: Priors"
              file: content/03-content.qmd
            - text: "4: Markov chain Monte Carlo"
              file: content/04-content.qmd
    - title: "Exercises"
      style: "docked"
      search: false
      foreground: "#000000"
      contents:
        - exercises/index.qmd
        - section: "1. Introduction"
          contents:
             - exercises/01-exercise.qmd
             - exercises/01-solution.qmd
        - section: "2. Bayesics"
          contents:
             - exercises/02-exercise.qmd
             #- exercises/02-solution.qmd
        - section: "3. Priors"
          contents:
             - exercises/03-exercise.qmd
             #- exercises/03-solution.qmd
        - section: "4. Metropolis--Hastings"
          contents:
             - exercises/04-exercise.qmd
             #- exercises/04-solution.qmd
        - section: "5. Gibbs sampling"
          contents:
             - exercises/05-exercise.qmd        
             #- exercises/05-solution.qmd
  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}})<br>
      Website template by [Dr. Andrew Heiss](https://www.andrewheiss.com/) under [MIT License](https://mit-license.org/)<br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})


preview:
  port: 6200
  browser: true
  watch-inputs: true
  navigate: true

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: github
