project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
  resources:
    - "files/"
    - "projects/"
    - "slides/*.html"
    - "slides/*.pdf"
    - "slides/img/"
    - "slides/libs/"
    - "slides/css/"
    - "slides/*_files/"

# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes

bibliography: files/bib/references.bib
csl: files/bib/apa.csl

website:
  title: "Bayesian modelling"
  site-url: "https://lbelzile.github.io/bayesmod"
  description: "Hands on introduction to Bayesian data analysis. The course will cover the formulation, evaluation and comparison of Bayesian models through examples."

  navbar:
    pinned: true
    background: "#ff585d"
    right:
      - syllabus.qmd
#      - schedule.qmd
      - text: "Content"
        file: content/index.qmd
      - text: "Exercises"
        file: exercises/index.qmd
      - text: "Evaluations"
        file: evaluations/index.qmd
      - text: "Notes"
        href: "https://lbelzile.github.io/MATH80601A/"
 #     - icon: box
 #       href: "https://lbelzile.github.io/hecbayesmod"
 #       aria-label: Datasets

  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      foreground: "#000000"
      contents:
        - section: "Overview"
          contents:
            - content/index.qmd
        - section: "Installation"
          contents:
            - text: "**R** and RStudio"
              file: content/installation.qmd
            - text: "**R** packages"
              file: content/rpackages.qmd
        - section: "Course content"
          contents:
            - text: "1: Introduction"
              file: content/01-content.qmd
            - text: "2: Bayesics"
              file: content/02-content.qmd
            - text: "3: Priors"
              file: content/03-content.qmd
            - text: "4: Monte Carlo, Markov chains and Metropolis-Hastings"
              file: content/04-content.qmd
            - text: "5: Gibbs sampling"
              file: content/05-content.qmd
            - text: "6: Bayesian workflow"
              file: content/06-content.qmd
            - text: "7: Probabilistic programming"
              file: content/07-content.qmd
            - text: "8: Bayesian regression"
              file: content/08-content.qmd
            - text: "9: Deterministic approximations"
              file: content/09-content.qmd
            - text: "10: Variational inference"
              file: content/10-content.qmd
    - title: "Exercises"
      style: "docked"
      search: false
      foreground: "#000000"
      contents:
        - "exercises/index.qmd"
        - section: "Exercises"
          contents:
             - text: "1. Introduction"
               file: exercises/01-exercise.qmd
             - text: "2. Bayesics"
               file: exercises/02-exercise.qmd
             - text: "3. Priors"
               file: exercises/03-exercise.qmd
             - text: "4. Monte Carlo methods"
               file: exercises/04-exercise.qmd
             - text: "5. Gibbs sampling"
               file: exercises/05-exercise.qmd
             - text: "6. Bayesian workflow"
               file: exercises/06-exercise.qmd
             - text: "9. Deterministic approximations"
               file: exercises/09-exercise.qmd
        - section: "Solutions"
          contents:
             - text: "1. Introduction"
               file: exercises/01-solution.qmd
             - text: "2. Bayesics"
               file: exercises/02-solution.qmd
             - text: "3. Priors"
               file: exercises/03-solution.qmd
             - text: "4. Monte Carlo methods"
               file: exercises/04-solution.qmd
             - text: "5. Gibbs sampling"
               file: exercises/05-solution.qmd
             - text: "6. Bayesian workflow"
               file: exercises/06-solution.qmd
             - text: "9. Deterministic approximations"
               file: exercises/09-solution.qmd
    - title: "Evaluations"
      style: "docked"
      search: false
      foreground: "#000000"
      contents:
         - evaluations/index.qmd
         - text: "Weekly check-in"
           file: evaluations/weekly-check-in.qmd
         - section: "Assignments"
           contents:
              - evaluations/01-assignment.qmd
              - evaluations/02-assignment.qmd
  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}})<br>
      Website template by [Dr. Andrew Heiss](https://www.andrewheiss.com/) under [MIT License](https://mit-license.org/)<br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})


preview:
  port: 6200
  browser: true
  watch-inputs: true
  navigate: true

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: github
