---
title: "Assignment 2"
toc: false
filters:
   - include-code-files
---

These problems are for credit and to be handed in on ZoneCours on March 10th at the latest at 15:30.

## Problem 2.1

The [`rats` data](/files/data/rats.csv), extracted from Table 5 of @Tarone:1982, contains observations from 70 experiments on  animal carcinogenesis bioassay
conducted with female F344 rats, recording the number of lung cancer tumors developed. Treating the observations as independent, write
\begin{align*}
y_i \mid \theta_i &\sim \mathsf{binom}(n_i, \theta_i), \quad i =1, \ldots, 70 \\
\theta_i \mid \alpha, \beta & \sim \mathsf{beta}(\alpha, \beta)
\end{align*}
with an improper prior $p(\alpha, \beta) = (\alpha + \beta)^{-5/2}\mathrm{I}(\alpha>0, \beta>0).$



1. Derive the conditional distributions of $p(\theta_i \mid \alpha, \beta, \boldsymbol{y})$, $p(\alpha \mid \beta, \boldsymbol{\theta})$ and $p(\beta \mid \alpha, \boldsymbol{\theta}).$
2. Implement a Gibbs sampling algorithm simulating from the conditionals $\boldsymbol{\theta} \mid \cdot,$ $\alpha \mid \cdot$ and $\beta \mid \cdot$ using one of the following methods:  rejection sampling (try an exponential distribution), ratio-of-uniform [@Wakefield:1991] via the **R** package [`rust`](https://doi.org/10.32614/CRAN.package.rust), adaptive rejection sampling [@Martino:2018;@Gilks.Wild:1992] via the [`ars`](https://doi.org/10.32614/CRAN.package.ars) **R** package^[Adaptive rejection sampling method works for log-concave distributions, which is the case for both the conditional of the hyperparameters $\alpha$ and $\beta$.] or slice sampling [@Neal:2003].^[If everything fails for you, you can use Metropolis]
3. Use instead a sampling algorithm with a Gibbs step for $\boldsymbol{\theta}$ and a random walk Metropolis--Hastings step for $\alpha$ and $\beta$. 
4. Reparametrize the model in terms of $\log(\beta)$ and $\log(\alpha)/\log(\beta)$ instead and run a Metropolis--Hasting step for the two parameters.
5. For each sampler and parametrization, plot the bivariate histogram/density/scatter plot for $(\alpha, \beta)$, plus correlograms for both parameters. Comment on the mixing of the algorithms.
 

## Problem 2.2

The purpose of this exercise is to explore different parametrizations and their impact on sampling. The  [`climatechange` data](/files/data/climatechange.csv) contains mean global temperature increases $T$ from the twenty year period 1970--1999 to projections 2069--2098 for different climate general circulation models (GCM), and sometimes multiple simulation runs for each GCM. The purpose of the analysis is to obtain a suitable mean temperature change globally for each representative concentration pathway (RCP, one of 2.6, 4.5, 6.0 and 8.5). The data were obtained from the `bang` **R** package and preprocessed to simplify the exposition, but see @Northrop.Chandler:2014 for pointers about the methodology.

The hierarchical structure for **Model A** and temperature $T$ for RCP $k$ and GCM $l$ is:
\begin{align*}
T_{k,l}\mid  \boldsymbol{\alpha}, \boldsymbol{\beta}, \tau &\sim \mathsf{Gauss}(\alpha_k + \beta_l, \tau^2)\\
\boldsymbol{\alpha} \mid \boldsymbol{\mu}, \omega &\sim \mathsf{Gauss}_4(\boldsymbol{\mu}, \omega^2\mathbf{I}_4)\\
\beta_l \mid \sigma &\sim \mathsf{Gauss}(0, \sigma^2), \qquad l = 1, \ldots, L.
\end{align*}

1. Prior elicitation: 
    a. what are your prior belief about climate change the range of plausible temperature increases? Write down suitable values for the means $\boldsymbol{\mu}$ and the standard deviation $\omega$ (which could be the same for all RCP) under different emission scenarios, if $\mu_1$ corresponds to RCP 2.6, $\mu_2$ to RCP 4.5, etc. and your guesses are non-decreasing.
    b. choose suitable priors for the scale parameters $\omega,$ $\tau$ and $\sigma$.
2. Reparametrizations: enforce a sum-to-zero hard constraint for $\beta_l$ versus soft-constraint (by reducing the variance and setting the prior to mean-zero). Indicate which works better for the problem based on considerations such as mixing and effective sample size.
3. For Model A, produce a caterpillar plot of the parameters $\beta_l$ ($l=1,\ldots, 38$) as follows: 
   a. obtain posterior mean for each random effect $\beta_l$ and sort them in increasing order
   b. for each parameter $\beta_l,$ obtain 80% equitailed credible intervals.
   c. plot the ordered point estimates and intervals against rank.
4. **Model B**: Consider forcing an ordering constraint for $\boldsymbol{\alpha}$, so that $\alpha_1 \leq \cdots \leq \alpha_4.$ What happens to the posterior?
    - Plot the marginal posterior density of $\alpha_1, \ldots, \alpha_4$ for the models with and without the ordering constraint and comment.
5. **Model C**:  keep RCP categorical, but let each emission scenario have it's own response variance $\sigma^2_k.$
6. **Model D**: Replace the categorical variables $\boldsymbol{\alpha}$ with a linear trend as a function of the value of RCP (i.e., treating the value of RCP as continuous rather than categorical).
7. Compare Models A to D: 
    - for each, compute the log likelihood for each posterior draw and use it to obtain the WAIC criterion. 
    - in addition perform posterior predictive checks for a suitable test function.
8. For a chosen adequate model, report the summary statistics of your procedure (posterior means, std. errors, range and effective sample size) for the variance parameters and the mean increase per RCP (or slope).


### Helper code for Problem 2.2

I am providing some Stan code (cross-platform) and show how to implement the model in **R** while defining suitable quantities, by casting the factors `RCP` and `GCM` to integer indicators.

```{r}
#| eval: false
#| echo: true
data(climatechange, package = "hecbayes")
# Transform factor name to integer for group assignment
GCM <- as.integer(climatechange$GCM)
data <- list(N = nrow(climatechange),
             K = 4L,
             L = max(GCM), # number of GCM provides
             y = climatechange$temp, # temperature series
             # Treat RCP as a factor (Model
             RCP = as.integer(factor(climatechange$RCP)),
             GCM = GCM,
             # TODO: add sensible prior values for mu
             mu = sort(rexp(4)))
cc_model <- cmdstanr::cmdstan_model(stan_file = "climatechange.stan")
cc_fit <- cc_model$sample(data = data, chains = 4L)
```

The following code enforces the sum-to-zero constraint for $\boldsymbol{\beta}$ (see [the Stan manual](https://mc-stan.org/docs/stan-users-guide/regression.html#parameterizing-centered-vectors)). You can get ordered vectors for $\boldsymbol{\alpha}$ by replacing `vector` by `ordered` below.

```{.stan include="climatechange.stan"}
```
