---
title: "Welcome to class"
date: "2025-01-03T18:15"
categories: [announcements]
---

Dear students, 

Welcome to Bayesian modelling, a PhD course offered by HEC Montréal. The course will cover the Bayesian paradigm from an applied perspective, focusing on statistical inference and prediction using a variety of statistical models. We will cover the basics of both main methods for inference: stochastic or simulation-based inference (using Markov chain Monte Carlo) and deterministic approximations (variational inference and the like). The course will say little about decision theory aspects (minimax estimation and admissibility, Haar measures and the like).

The (informal) prerequisites for this course are [MATH 20602](https://www.hec.ca/cours/detail/?cours=MATH20602) and [MATH 60604](https://www.hec.ca/cours/detail/?cours=MATH60604), or equivalent. This covers univariate and multivariate discrete and continuous distributions, changes of variables, basic of Monte Carlo inference and Markov chains. Students are expected to be familiar with basic regression models.

This is the first iteration of the course, so much of the material is still work in progress and will be released progressively. I will likely update slides or notes after class to fix typos or to add clarification. In this optic, you will also be asked through a weekly check-in to provide feedback on the course content. There, you can identify muddled topics, unclear statements, good examples, etc.

From a programming perspective, basic Markov chain Monte Carlo methods can be implemented in R, Python, Julia, etc. I will provide code for the former. Later, we will access probabilistic programming languages such as Stan, and there are interfaces for the latter.

A couple of quick points

- We are meeting in person, but it is useful to read course notes ahead of class. Class time will be dedicated to a question period, going over the exercises from the previous week (over roughly the first half-hour). I will then cover part of the material, but some content may be recorded to allow for more interaction in-person.
- Every week, you will be given exercises (some for credit, roughly one per week) and others not to be handed in. Practice is of paramount importance for assimilating concepts, etc. Problem sets will be broken down in three assignments (the plan is to have 3 points per problem, over 10 weeks).
- There are numerous references for this course, most of which I **don't** intend to follow. The course content is available at the address <https://lbelzile.github.io/bayesmod/> and the course notes will be at  <https://lbelzile.github.io/MATH80601A/>. You can bookmark these URLs directly and refer to them, even if I have embedded them in ZoneCours. 

Looking forward to meeting you,

Léo
