---
title: "Priors"
date: "2023-09-26"
---


## Content

- Conjugate, flat, vague, Jeffrey's, informative and penalized complexity priors
- Priors for regression models
- Parameter elicitation
- Prior sensitivity analysis

## Learning objectives

At the end of the chapter, students should be able to

- choose a suitable prior for a Bayesian analysis
- derive parameters of posterior distributions in conjugate models
- perform parameter elicitation
- assess the impact of priors through sensitivity analysis

## Readings

:::{.callout-warning}

These readings should be completed before class, to ensure timely understanding and let us discuss the concepts together through various examples and case studies --- the strict minimum being the course notes.

:::


- [Chapter 2 of the course notes](https://lbelzile.github.io/MATH80601A/priors.html)


## Complementary readings

:::{.callout-warning}
Complementary readings are additional sources of information that are not required readings, but may be useful substitutes. Sometimes, they go beyond the scope of what we cover and provide more details.
:::


- @Villani:2023, chapter 4
- @Gelman:2013, chapters 2, 3 and 5
- @Johnson.Ott.Dogucu:2022, [chapter 5](https://www.bayesrulesbook.com/chapter-5)



- truncated Student-t priors for hierarchical models [@Gelman:2006]
- penalized complexity priors [@Simpson:2017]

## Slides


<p class="text-center"><a class="btn btn-success btn-lg" target="_blank" href="../slides/bayesmod-slides2.html">{{< fa arrow-up-right-from-square >}} &ensp;View all slides in new window</a> <a class="btn btn-success btn-lg" target="_blank" href="../slides/bayesmod-slides2.pdf" role="button">{{< fa file-pdf >}} &ensp;Download PDF of all slides</a></p>

<div class="ratio ratio-16x9">
<iframe class="slide-deck" src="../slides/bayesmod-slides2.html"></iframe>
</div>
