---
title: "Monte Carlo methods"
---


## Content

- Monte Carlo methods: rejection sampling, importance sampling
- Basics of Markov chains



## Learning objectives

At the end of the chapter, students should be able to

- simulate from target distribution using rejection sampling
- estimate integrals using importance sampling
- explain under which circumstances can Markov chain output can be used in place of independent Monte Carlo
- calculate standard errors for sample means of Markov chain
- understand the inefficiency due to autocorrelation of Monte Carlo integration based on draws from Markov chains.

## Readings


- [@Geyer:2011](https://www.cs.tufts.edu/~nr/cs257/archive/charles-geyer/mcmctutorial.pdf) --- up to 1.17
- [Chapters 4](https://lbelzile.github.io/MATH80601A/montecarlo.html) [and 5](https://lbelzile.github.io/MATH80601A/mcmc.html) of the course notes


## Complementary readings

- @Green:2015 (overview of MCMC methods)


## Slides


<p class="text-center"><a class="btn btn-success btn-lg" target="_blank" href="../slides/bayesmod-slides4.html">{{< fa arrow-up-right-from-square >}} &ensp;View all slides in new window</a> <a class="btn btn-success btn-lg" target="_blank" href="../slides/bayesmod-slides4.pdf" role="button">{{< fa file-pdf >}} &ensp;Download PDF of all slides</a></p>


<div class="ratio ratio-16x9">
<iframe class="slide-deck" src="../slides/bayesmod-slides4.html"></iframe>
</div>


## Code


- [Code demonstration](04-lecture.qmd)

