---
title: "MCMC and Gibbs sampling"
---


## Content

- Metropolis-adjusted Langevin algorithm (MALA)
- Gibbs sampling
- Data augmentation
- Graphical diagnostics of convergence
- Goodness-of-fit measures (WAIC, LOO-CV, etc.)

## Learning objectives

At the end of the chapter, students should be able to

- implement Gibbs sampling
- derive the conditional distributions of a model for Gibbs sampling
- choose suitable test statistics to evaluate model adequacy
- assess convergence using graphical tools and effective sample size
- perform model comparisons using Bayes factor or predictive measures




## Readings

:::{.callout-warning}

These readings should be completed before class, to ensure timely understanding and let us discuss the concepts together through various examples and case studies --- the strict minimum being the course notes.

:::

- [Chapter 6](https://lbelzile.github.io/MATH80601A/gibbs.html) 


## Complementary readings

:::{.callout-warning}
Complementary readings are additional sources of information that are not required readings, but may be useful substitutes. Sometimes, they go beyond the scope of what we cover and provide more details.
:::


- @Gelman:2013, chapters 6 and 7
- @Albert:2009, chapters 6 and 10 (several examples)
- @McElreath:2020, chapter 9.5 


## Slides


<p class="text-center"><a class="btn btn-success btn-lg" target="_blank" href="../slides/bayesmod-slides6.html">{{< fa arrow-up-right-from-square >}} &ensp;View all slides in new window</a> <a class="btn btn-success btn-lg" target="_blank" href="../slides/bayesmod-slides6.pdf" role="button">{{< fa file-pdf >}} &ensp;Download PDF of all slides</a></p>


<div class="ratio ratio-16x9">
<iframe class="slide-deck" src="../slides/bayesmod-slides6.html"></iframe>
</div>

## Code


- [Code demonstration](06-lecture.qmd)
- [**R** script](/files/code/06-mixture.R) for two-component mixture model

<!--
- [**R** script](/files/code/06-Tokyo_rainfall.R) for the Tokyo rainfall
-->
