---
title: "Regression models"
---


## Content

- Bayesian linear model
- Priors for covariance matrices
- Shrinkage prior
- Bayesian model averaging

## Learning objectives

At the end of the chapter, students should be able to

- code a Gaussian linear model using Gibbs sampling
- determine suitable priors for correlated random effects
- understand the methodology behind shrinkage priors



## Readings

- [Chapter 8](https://lbelzile.github.io/MATH80601A/regression.html) of the course notes

## Complementary readings

- @Mitchell.Beauchamp:1988, @George.McCulloch:1993 (spike and slab priors)
- @Geweke:1992 (Bayesian linear model)
- @Carvalho.Polson.Scott:2010, @Piironen.Vehtari:2017 (horseshoe priors)
<!-- - @Bove.Held:2011 (Zellner $g$-prior for GLM) -->
- @vanErp:2019 (comparison of shrinkage priors)
- @Hoeting:1999, Holmes:2002 (Bayesian model averaging)


## Slides


<p class="text-center"><a class="btn btn-success btn-lg" target="_blank" href="../slides/bayesmod-slides8.html">{{< fa arrow-up-right-from-square >}} &ensp;View all slides in new window</a> <a class="btn btn-success btn-lg" target="_blank" href="../slides/bayesmod-slides8.pdf" role="button">{{< fa file-pdf >}} &ensp;Download PDF of all slides</a></p>


<div class="ratio ratio-16x9">
<iframe class="slide-deck" src="../slides/bayesmod-slides8.html"></iframe>
</div>

## Code

- Gaussian regression [**R** script](/files/code/08-gaussianregression.R)
- Horseshoe prior [**R** script](/files/code/08-horseshoe.R) and [Stan script](/files/code/08-horseshoe.stan)
