{
  "hash": "22b13f0c54a3068458ba538b91c8bfca",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Solution 4\"\n---\n\n\n## Exercise 4.1\n\nConsider the Laplace family of distribution, $\\mathsf{Laplace}(\\nu, \\tau)$, with density\n\\begin{align*}\ng(x; \\nu, \\tau) = \\frac{1}{2\\tau} \\exp\\left(- \\frac{|x-\\nu|}{\\tau}\\right), \\qquad \\nu \\in \\mathbb{R}, \\tau > 0\n\\end{align*}\nas a candidate distribution for rejection sampling from $\\mathsf{Gauss}(0,1)$.\n\n1. Provide an inversion sampling algorithm to generate from $\\mathsf{Laplace}(\\nu, \\tau)$.\n2. Can you use the proposal to generate from a standard Gaussian? for Student-$t$ with 1 degree of freedom? Justify your answer.\n3. Consider as proposal a location-scale version of the Student-t with $3$ degrees of freedom. Find the optimal location and scale parameters and the upper bound $C$ for your choice.\n4. Use the accept-reject to simulate 1000 independent observations and compute the empirical acceptance rate.\n\n\n\n::: {.solution}\n\n1. The distribution function is \n\\begin{align*}\nF(x) = \\begin{cases}\n\\frac{1}{2} \\exp\\left(\\frac{x-\\nu}{\\tau}\\right) & x \\leq \\nu\\\\\n1 - \\frac{1}{2} \\exp\\left(-\\frac{x-\\nu}{\\tau}\\right) & x >\\nu\\\\\n\\end{cases}\n\\end{align*}\nand using the quantile transform, set $X=\\nu + \\tau \\log(2U)$ if $U \\leq 0.5$ and $X=\\nu - \\tau\\log(2-2U)$ if $U > 0.5$ for $U \\sim \\mathsf{unif}(0,1)$.\n2. The Gaussian has lighter tail than the Laplace, so this won't work. The Cauchy distribution would be a suitable candidate, albeit too heavy tailed.\n3. The optimal value for the location of the Student-$t$ would be $\\nu$ (e.g., zero for the standard Laplace). We compute the optimal scale via in the code below:\n$$\n\\mathrm{argmin}_{\\sigma \\in \\mathbb{R}_{+}}\\mathrm{argmax}_{x \\in \\mathbb{R}} \\{\\log f(x) - \\log g(x; \\sigma)\\}\n$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#' Laplace density\ndlaplace <- function(x, loc = 0, scale = 1, log = FALSE){\n stopifnot(scale > 0)\n logdens <-  -log(2*scale) - abs(x-loc)/scale\n if(log){\n return(logdens)\n } else{\n return(exp(logdens))\n }\n}\ndstudent <- function(x, loc = 0, scale = 1, df = 1, log = FALSE){\n  logdens <- -log(scale) + dt(x = (x - loc)/scale, df = df, log = TRUE)\n   if(log){\n    return(logdens)\n   } else{\n   return(exp(logdens))\n   }\n}\n# For each value of the scale sigma,\n# find the minimum value of x (typically at zero)\nopt <- optimize(f = function(sigma){\n  optimize(f = function(x){\n  dlaplace(x, log = TRUE) - \n    dstudent(x, scale = sigma, df = 3, log = TRUE)}, \n  maximum = TRUE, \n  interval = c(-100, 100))$objective\n}, interval = c(0.1,10))\n(C <- exp(opt$objective))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.261368\n```\n\n\n:::\n\n```{.r .cell-code}\n(sigma <- opt$minimum)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9272381\n```\n\n\n:::\n\n```{.r .cell-code}\n# Simulate from accept-reject\nntrials <- 1.1*C*1000\n# Simulate from location-scale student\ncandidate <- sigma*rt(n = ntrials, df = 3)\n# Compute log of acceptance rate\nlogR <- dlaplace(candidate, log = TRUE) - \n  dstudent(candidate, scale = sigma, df = 3, log = TRUE) \nsamp <- candidate[logR >= log(C) + -rexp(ntrials)]\n# Monte Carlo estimator of the acceptance rate\nntrials/length(samp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.27528\n```\n\n\n:::\n\n```{.r .cell-code}\n# Plot density\nlibrary(ggplot2)\nggplot(data = data.frame(x = samp),\n       mapping = aes(x = x)) +\n  geom_density() +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](04-solution_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n4. The Monte Carlo acceptance rate is 1.28, compared with the analytical bound found via numerical optimization of 1.26, to two significant digits.\n\n:::\n\n\n## Exercise 4.2\n\nWe revisit [Exercise 2.3](/exercises/02-exercise.html#exercice-2.3), which used a half-Cauchy prior for the exponential waiting time of buses.\n\nThe ratio-of-uniform method, implemented in the [`rust` **R** package](https://paulnorthrop.github.io/rust/index.html), can be used to simulate independent draws from the posterior of the rate $\\lambda$.\nThe following code produces \n\n::: {.cell}\n\n```{.r .cell-code}\nnobs <- 10L # number of observations\nybar <- 8   # average waiting time\nB <- 1e4L  # number of draws\n# Un-normalized log posterior: scaled log likelihood + log prior\nupost <- function(x){ \n  dgamma(x = x, shape = nobs + 1L, rate = nobs*ybar, log = TRUE) +\n    log(2) + dt(x = x, df = 1, log = TRUE)}\npost_samp <- rust::ru(logf = upost, \n                      n = B, \n                      d = 1,  # dimension of parameter (scalar)\n                      init = nobs/ybar)$sim_vals # initial value of mode\n```\n:::\n\n\nEstimate using the independent Monte Carlo samples:\n\n1. the probability that the average waiting time $1/\\lambda$ is between 3 and 15 minutes\n2. the average waiting time\n3. the standard deviation of the average waiting time.\n\n\nNext, implement a random walk Metropolis--Hastings algorithm to sample draws from the posterior and re-estimate the quantities. Compare the values.\n\n::: {.solution}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Monte Carlo for waiting time\n# Lambda is the reciprocal mean (1/minute)\ntimes_mc <- 1/post_samp\n# Mean of binary variables + std. error\np <- mean(times_mc > 3 & times_mc < 15)\nc(est = p, se = sqrt(p*(1-p)/B))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        est          se \n0.981400000 0.001351075 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Posterior mean with standard error\nc(est = mean(times_mc), se = sd(times_mc)/sqrt(length(post_samp)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       est         se \n7.99081905 0.02612151 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Metropolis-Hastings algorithm\nB <- 1e4L\ncurr <- 8/10 # prior mean\nchains <- numeric(B) # container\nsd_prop <- 0.1 # proposal standard deviation\nfor(b in seq_len(B)){\n  prop <- rnorm(n = 1, mean = curr, sd = sd_prop)\n  if(upost(prop) - upost(curr) > -rexp(1)){\n    curr <- prop\n  }\n  chains[b] <- curr\n}\n# Discard burn-in\ntimes <- 1/chains[-(1:100)]\n# Estimate quantities using Monte Carlo\nmean(times > 3 & times < 15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9793939\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(times)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8.069608\n```\n\n\n:::\n\n```{.r .cell-code}\nsd(times)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.707214\n```\n\n\n:::\n\n```{.r .cell-code}\n# Summary of MCMC\nmcmc <- coda::mcmc(times)\nsummary(mcmc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nIterations = 1:9900\nThinning interval = 1 \nNumber of chains = 1 \nSample size per chain = 9900 \n\n1. Empirical mean and standard deviation for each variable,\n   plus standard error of the mean:\n\n          Mean             SD       Naive SE Time-series SE \n       8.06961        2.70721        0.02721        0.05760 \n\n2. Quantiles for each variable:\n\n  2.5%    25%    50%    75%  97.5% \n 4.388  6.169  7.576  9.330 14.695 \n```\n\n\n:::\n:::\n\nWe can see that the standard error for the mean is roughly twice as big. We would thus need to inflate the sample size by a factor four to get the same precision.\n\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}