---
title: "Exercises 5"
---



## Exercise 5.1

The Pareto distribution with shape $\alpha>0$ and scale $\tau>0$ has density
$$
f(x; \alpha, \tau) = \alpha x^{-\alpha-1}\tau^\alpha \mathrm{I}(x > \tau).
$$
It can be used to model power laws in insurance and finance, or in demography. The `uscitypopn` data set in the `hecbayes` package contains the population size of cities above 200K inhabitants in the United States, from the 2020 census.

1. Using improper priors $p(\alpha, \tau) \propto 1,$ write the joint posterior for a simple random sample of size $n$ and derive the conditional distributions $p(\alpha \mid \boldsymbol{y}, \tau)$ and $p(\tau \mid \alpha, \boldsymbol{y})$. *Hint*: the conditional density $p(\alpha \mid \boldsymbol{y}, \tau)$ is that of a gamma; use the fact that $m^\alpha=\exp\{\alpha\log(m)\}$ for $m>0$.
2. The mononomial distribution $\mathsf{Mono}(a,b)$ has density $p(x) \propto x^{a-1}\mathsf{I}(0 \leq x \leq b)$ for $a, b > 0$. Find the normalizing constant for the distribution and obtain the quantile function to derive a random number generator.
3. Implement Gibbs sampling for this problem for the `uscitypopn` data. Draw enough observations to obtain an effective sample size of at least 1000 observations. Calculate the accuracy of your estimates.


## Exercise 5.2

Consider the following code which implements a Metropolis--Hastings algorithm to simulate observations from a $\mathsf{beta}(0.5, 0.5)$ density.

```{r}
#| echo: true
#| eval: false
log_f <- function(par){
  dbeta(x = par, shape1 = 0.5, shape2 = 0.5, log = TRUE)
}
metropo <- function(B, sd_prop = 0.2){
  chain <- rep(0, B)
  # Draw initial value
  cur <- runif(1)
  for(b in seq_len(B)){
    repeat {
        # Simulate proposal from Gaussian random walk proposal
        prop <- cur + rnorm(1, sd = sd_prop)
        # check admissibility for probability of success
        if (prop >= 0 & prop <= 1)
          break
    }
    # Compute (log) acceptance ratio
    logR <- log_f(prop) - log_f(cur) 
    # Accept the move if R > u
    if(isTRUE(logR > log(runif(1)))){
     cur <- prop 
    }
    chain[b] <- cur
  }
  return(chain)
}
# Run MCMC for 10K iterations
mc <- metropo(1e4L)
```

To see if the algorithm works:

a. Plot the density of the Markov chain draws along with the beta density curve. 
b. Check that empirical moments match the theoretical ones

If the algorithm is incorrect, provide a fix and explain the reason for the problem.



## Exercise 5.3

Implement the Bayesian LASSO for the `diabetes` cancer surgery from package `lars`.  Check @Park.Casella:2008 for the details of the Gibbs sampling (p. 682, right column).

1. Fit the model for a range of values of $\lambda$ and produce parameter estimate paths to replicate Figure 2 of the paper.
2. Check the effective sample size and comment on the mixing. Is it impacted by the tuning parameter?
3. Implement the method of section 3.1 from @Park.Casella:2008 by adding $\lambda$ as a parameter.
<!--4. For three models with different values of $\lambda$, compute the widely applicable information criterion (WAIC) and use it to assess predictive performance. -->
