---
title: "Exercises 6"
---


## Exercise 6.1

Consider the eight school data.

Consider a one-way ANOVA with $K$ categories, with observation $i$ from group $k$ having
\begin{align*}
Y_{i,k} &\sim \mathsf{Gauss}(\mu + \alpha_k, \sigma^2_y) \\
\alpha_k &\sim \mathsf{Gauss}(0, \sigma^2_\alpha)
\end{align*}
and an improper prior for the mean $p(\mu) \propto 1.$
If there are $K$ groups, then the group-specific mean is $\mu+\alpha_k$, and there is a redundant parameter. In the Bayesian setting, the parameters are weakly identifiable because of the prior on $\boldsymbol{\alpha}$.

Add redundant parameter to improve mixing by decorrelating [@Liu.Rubin.Wu:1998]

\begin{align*}
Y_{i,k} &\sim \mathsf{Gauss}(\mu + \xi\eta_k, \sigma^2_y) \\
\eta_k &\sim \mathsf{Gauss}(0, \sigma^2_\eta)
\end{align*}
so that $\sigma_\alpha = |\xi|\sigma_\eta.$


Run four Markov chains to estimate the parameters with different starting values and store the posterior parameters. For each posterior draw, sample a corresponding data set from the posterior predictive with the same size as the original.

1. Plot the chain including burn in and warmup period. How many iterations does it take for the chains to stabilize?
2. Estimate the quartiles and report adjusted Monte Carlo standard errors based on the effective sample size.
3. Calculate the $\widehat{R}$ factor for each parameter.
4. **Posterior predictive check**: for each simulated dataset from the posterior predictive,
     a. plot their density and compare with that of the original data.
     b. Compare the posterior std. deviation and the range.
     c. Compute the leave-one-out cross validated probability integral transform
5. Compute WAIC



## Exercise 6.2

Let $Y_{ij1}$ ($Y_{ij2}$) denote the score of the home (respectively visitor) team for a soccer match opposing teams $i$ and $j$. @Maher:1982 suggested modelling the scores as
\begin{align*}
Y_{ij1} \mid \delta, \alpha_i, \beta_j &\sim \mathsf{Poisson}\{\exp(\delta + \alpha_i +\beta_j)\},
\\ Y_{ij2} \mid \delta, \alpha_j, \beta_i &\sim \mathsf{Poisson}\{\exp(\alpha_j+\beta_i)\},
\end{align*}
where 

- $\alpha_i$ represent the offensive strength of the team, 
- $\beta_j$ the defensive strength of team $j$ and 
- $\delta$ is the common home advantage. 

The scores in a match and between matches are assumed to be conditionally independent of one another given $\boldsymbol{\alpha}, \boldsymbol{\beta}, \delta$. The data set `soccer` contains the results of football (soccer) matches for the 2015 season of the English Premier Ligue (EPL) and contains the following variables

- `score`: number of goals of `team` during a match
- `team`: categorical variable giving the name of the team which scored the goals
- `opponent`: categorical variable giving the name of the adversary
- `home`: binary variable, 1 if `team` is playing at home, 0 otherwise.


1. Specify suitable priors for the regression parameters that shrink $\alpha_i$ and $\beta_j$ to zero.
2. Fit the model characterized using the frequentist estimates as starting values and answer the following questions: 
   - Using the posterior distribution, give the expected number of goals for a match between Manchester United (at home) against Liverpool.
   - Report and interpret the estimated posterior mean home advantage $\widehat{\delta}$. 
   - Calculate the probability that the home advantage $\delta$ is positive?
3. Comment on the adequacy of the fit by using a suitable statistic for the model fit (e.g. the deviance statistic
4. Maher also suggested more complex models, including one in which the offensive and defensive strength of each team changed depending on whether they were at home or visiting another team, i.e.
\begin{align}
Y_{ij1} \sim \mathsf{Poisson}\{\exp(\alpha_i +\beta_j + \delta)\}, 
Y_{ij2} \sim \mathsf{Poisson}\{\exp(\gamma_j+\omega_i)\},
\end{align}
Does the second model fit significantly better than  than the first? Compare the models using WAIC and Bayes factors.

## Exercise 6.3

The 2000 US presidential election opposed Georges W. Bush (GOP) and Albert A. Gore (Democrat), as well as marginal third party candidates. The tipping state was Florida, worth 25 electors, which Bush won by a narrow margin of 537 votes.  There have been many claims that the design of so-called [butterfly ballot](https://www.palmbeachpost.com/storyimage/LK/20151105/NEWS/812069858/AR/0/AR-812069858.jpg) used in poor neighborhoods of Palm Beach county led to confusion among voters and that this deprived Gore of some thousands of votes that were instead assigned to a paleoconservative third-party candidate, Patrick Buchanan (Reform). @Smith:2002 \href{https://projecteuclid.org/euclid.ss/1049993203}{Smith (2002)} analysed the election results in Palm Beach country, in which a unusually high number of ballots (3407) were cast for Buchanan. 

We are interested in building a model to predict the expected number of votes for Buchanan in Palm Beach county, based only on the information from other county votes. The data set `buchanan` contains sociodemographic information and votes per county of different candidates.

1. Plot the percentage of votes obtained by Buchanan, `buch`/(`buch`+`totmb`), against $\log$`popn` and comment.
2. Fit a binomial logistic model for the votes of Bush versus Gore with $\log$ `popn`, `black`, `hisp`, `geq65` `highsc` as covariates. 
    - Interpret the estimated coefficients $\widehat{\boldsymbol{\beta}}$ for `highsc` and `hisp` on the odds scale.
    - Calculate the total posterior proportion of votes for Buchanan in Florida.
3. Look at the posterior predictive checks and leave-one-out probability plot.  Is there evidence of overdispersion? Consider how to account for the latter and compare the model with a beta-binomial regression.
4. Rerun the model **excluding** the results of Palm Beach county and predict the expected number of Buchanan votes in Palm Beach county. Comment hence on the discrepancy between this forecast and the number of votes received in the election.
