{
  "hash": "0e184b1be4a3eb6ef8cb18f4b512a4e4",
  "result": {
    "markdown": "---\ntitle: \"Solution 1\"\n---\n\n\n\nYou consider the waiting times between buses coming to HEC. Your bus line has frequent buses, but you decide to check the frequency. From your prior experience, you know that measured waiting times range between 3 and 15 minutes. You collect data over the two first week of classes and get an average of 8 minutes based on 10 observations.\n\nFor modelling, we consider data to arise an independent and identically distributed sample from an exponential distribution with rate $\\lambda>0$, with associated density $f(x) = \\lambda \\exp(-\\lambda x)$.\n\n## Exercise 1.1\n\n\nCompute the marginal likelihood when the prior for $\\lambda$ is \n\n1. an exponential distribution with rate $\\kappa>0$, with prior density $p(\\lambda) = \\kappa \\exp(-\\lambda\\kappa)$;\n2. same, but truncated above at 1, so the density is $p(\\lambda) = \\kappa \\exp(-\\lambda\\kappa)\\mathrm{I}\\{\\lambda \\leq 1\\}$; the indicator function $\\mathrm{I}(\\cdot)$ equals one if the condition is true and zero otherwise.\n3. $\\lambda \\sim \\mathsf{Ga}(\\alpha, \\beta)$, a gamma distribution with shape $\\alpha>0$ and rate $\\beta>0$, with prior density $p(\\lambda) = \\beta^\\alpha\\lambda^{\\alpha-1}\\exp(-\\beta \\lambda)/\\Gamma(\\alpha)$.\n\nDeduce that, in all cases above and up to truncation, the posterior distribution is a gamma distribution.\n\n::: {.solution}\nThe likelihood is\n\\begin{align*}\nL(\\lambda) = \\prod_{i=1}^n \\lambda \\exp(-\\lambda y_i) = \\lambda^n \\exp(-\\lambda n\\overline{y}),\n\\end{align*}\nwhere $\\overline{y}=8$ is the sample mean and $n=10$ the number of observations.\n\nThe exponential distribution is a special case of the gamma, where $\\lambda \\sim \\mathsf{Exp}(\\kappa) \\equiv \\mathsf{Ga}(1, \\kappa)$.\n\nThe posterior densities are equal, up to proportionality, to\n\\begin{align*}\np_1(\\lambda \\mid y) &\\propto\\lambda^{n}\\exp\\{-(n\\overline{y}+\\kappa)\\lambda\\} \\\\\np_2(\\lambda \\mid y) &\\propto\\lambda^{n}\\exp\\{-(n\\overline{y}+\\kappa)\\lambda\\}\\mathrm{I}\\{\\lambda \\geq 1\\} \\\\\np_3(\\lambda \\mid y) &\\propto\\lambda^{n+\\alpha-1}\\exp\\{-(n\\overline{y}+\\beta)\\lambda\\}\n\\end{align*}\nso these are $\\mathsf{Ga}(n+1, n\\overline{y} + \\kappa)$, $\\mathsf{Ga}(n+1, n\\overline{y} + \\kappa)$ truncated over $[0,1]$ and $\\mathsf{Ga}(n+\\alpha, n\\overline{y} + \\beta)$.\n\nLet $\\Gamma(\\cdot)$ denote the gamma function and $\\gamma(a, x)$ the lower incomplete gamma function, $\\gamma(a, x= \\int_0^x t^{a-1}\\exp(-t) \\mathrm{d} t.$ The **marginal likelihood** can be obtained either by integrating the product of the likelihood and prior, or upon noting that  \n\\begin{align*}\np_i(\\boldsymbol{y}) = \\frac{L(\\lambda) p_i(\\lambda)}{p_i(\\lambda \\mid \\boldsymbol{y})}\n\\end{align*}\nso we get \n\\begin{align*}\np_1(\\boldsymbol{y}) &= \\kappa n!(n\\overline{y}+\\kappa)^{-(n+1)},\\\\ \np_2(\\boldsymbol{y}) &= p_1(\\boldsymbol{y}) \\times \\gamma\\{n+1, (n\\overline{y}+\\kappa)\\}, \\\\ \np_3(\\boldsymbol{y}) &= \\frac{\\Gamma(n + \\alpha)\\beta^\\alpha}{\\Gamma(\\alpha)(n\\overline{y} + \\beta)^{n+\\alpha}}.\n\\end{align*}\n\n\n::: {.cell}\n\n:::\n\n\n:::\n\n\n## Exercise 1.2\n\nConsider the following priors\n\n1. a gamma distribution with rate $\\beta=10$ and shape $\\alpha = 50$\n2. an exponential distribution with rate 5\n3. a gamma distribution with rate $\\beta=0.02$ and shape $\\alpha = 14$\n4. a uniform prior on the unit interval [5,10]\n\nAssociate each plot of the posterior with each of the priors. Which one seems most suitable for modelling?\n\nExplain what would happen to the posterior curve if we increased the sample size.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Posteriors (full) and scaled likelihood (dashed) for exponential data, with different priors.](01-solution_files/figure-html/fig-betabinom-1.png){#fig-betabinom width=672}\n:::\n:::\n\n\n::: {.solution}\n\n\nAs the sample size increase, the curve becomes more concentrated around the maximum a posteriori value, which approaches the maximum likelihood estimator regardless of the prior function (if it is untruncated).\n\nThe truncated distribution (bottom left) is clearly identified from the \"stubborn\" prior, so 4C. Prior 3 has an average of 7, both the remaining two have a mean of 5, so 3D. We can look at how pronounced the posterior are: the $\\mathsf{Ga}(50,10)$ is much more informative and the posterior mean is closer to the prior mean, so 1A and so 2B.\n\n:::\n\n\n## Exercice 1.3\n\n\n\nThe purpose of this exercise is to show that even one-dimensional numerical integration requires some care.\nConsider a half Cauchy prior over the positive half line, with density $f(x) = 2\\pi^{-1}(1+x^2)^{-1}\\mathrm{I}(x \\geq 0)$. Using a grid approximation in increments of 0.01, evaluate the unnormalized posterior density from 0 until 30 minutes$^{-1}$. Compare this approximation with that of quadrature methods via `integrate` and return the corresponding estimates of the normalizing constant. *Indication*: check the values and make sure the output is sensical. Modify the integrand if necessary.\n\nPlot the posterior distribution of $\\omega = 1/\\lambda$, the average waiting time.\n\n\n::: {.solution}\n\nFor an unnormalized density $g(x)$ such that $\\int g(x) \\mathrm{d} x = c$, the normalizing constant is $1/c$.\n\nFirst, remember that the density function of the scale $\\omega = \\lambda^{-1}$ is related to the one of the rate $\\lambda$ through a change of variable, with Jacobian $\\omega^{-2}$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Likelihood function - NOTE FORMULATION TO AVOID NUMERICAL OVERFLOW\nlik <- function(x, n = 10, ybar = 8){exp(n*(log(x)-ybar*x))}\n# Density of Cauchy over positive real line\ndfoldedCauchy <- function(x){2/pi/(1+x^2)}\n# Check integral\nintegrate(dfoldedCauchy, lower = 0, upper = Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n1 with absolute error < 1.6e-10\n```\n:::\n\n```{.r .cell-code}\n# Unormalized posterior\nunnorm_post <- function(x){dfoldedCauchy(x)*lik(x)}\n(icst_lambda <- integrate(f = unnorm_post, 0, 100))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n7.074775e-15 with absolute error < 1.4e-14\n```\n:::\n\n```{.r .cell-code}\n# Check that the normalized value gives integral of 1\ncst_test <- integrate(f = function(x){unnorm_post(x)/icst_lambda$value}, \n                      lower = 0,\n                      upper = 100)\n```\n:::\n\n\nOuch! The integral is nearly zero, and there is significant risk of numerical underflow and the reciprocal of the integrals are one order of magnitude apart, even when the sample size is not large. The normalizing constant, the reciprocal of the marginal likelihood, is not well estimated.  The absolute error is of higher order than the estimate  of the marginal likelihood, and this will be more problematic in higher dimensions.\n\nTo palliate to this, we could slightly modify the integrand by scaling the likelihood by $(n\\overline{y} )^{n+1}/n!$, the normalizing constant of the gamma integral, which is around $2.4 \\times 10^{14}$. This fixes the issue below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Scale likelihood by using gamma distribution normalizing constant\nslik <- function(x, n = 10, ybar = 8){\n  exp(-lgamma(n+1) + (n+1)*log(n*ybar) + n*(log(x)-ybar*x))\n}\n# Unnormalized posterior, version 2\nunnorm_post2 <- function(x){dfoldedCauchy(x)*slik(x)}\n# Define grid and evaluate product\ngrid <- seq(from = 0, to = 30, by = 0.01)\nmarglik_grid <- sum(unnorm_post2(grid))*0.01\n# Is the grid approximation good enough?\n# check equality to numerical tolerance\nall.equal(integrate(f = unnorm_post2, 0, 100)$value, marglik_grid)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n\n```{.r .cell-code}\nnorm_cst <- 1/marglik_grid\n```\n:::\n\n\nThe prior normalizing by a known constant fixes the numerical issues. Generally, one would tend to build an approximation only at the mode and match the curvature of the posterior there (using, e.g., a quadratic approximation to the posterior density).\n\n\nFor the posterior density, we can simply use the approximation with $p(\\lambda \\mid \\boldsymbol{y}) \\approx \\widehat{c} L(\\lambda)p(\\lambda)$. The posterior density for the reciprocal rate is $p(\\omega \\mid \\boldsymbol{y}) \\approx \\widehat{c} L(\\omega^{-1})p(\\omega^{-1})\\omega^{-2}$ (don't forget the Jacobian)!\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(ggplot2)\nggplot() + \n  stat_function(fun = function(x){unnorm_post2(1/x)*norm_cst/x^2},\n                xlim = c(0, 30),\n                n = 1001) +\n  labs(y = \"\", \n       x = expression(paste(\"average waiting time \", 1/lambda, \" (in minutes)\")),\n       subtitle = \"posterior density\") + \n  scale_y_continuous(limits = c(0, NA), expand = expansion(mult = c(0, .1))) +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](01-solution_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n:::\n\n\n\n## Exercice 1.4\n\nConsider $\\lambda \\sim \\mathsf{Ga}(\\alpha = 1.4, \\beta=0.2)$.\n\n1. Return the posterior mean, posterior median and maximum a posteriori (MAP).\n2. Return the 89% equitailed percentile credible interval.\n3. Return the 50% highest posterior density (HPD) interval (harder).\n\nNext, draw 1000 observations from the posterior predictive distribution and plot a histogram of the latter. Compare it to the exponential distribution of observations.\n\nWould the posterior predictive change if you gathered more data? Justify your answer and explain how it would change, if at all.\n\n::: {.solution}\n\nWe have already determined that the posterior is a Gamma distribution $\\mathsf{Ga}(a, b)$, where $a= \\alpha+ n= 11.4$ and $b=n\\overline{y} + \\beta = 80.2$. We can query the moments directly: the mode is $(a-1)/b$ and the mean $a/b$, while the median must be found numerically using the quantile function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\na <- 11.4 # shape parameter\nb <- 80.2 # rate parameter\nalpha <- 0.11 # level\npostmean <- a/b # posterior mean\npostmed <- qgamma(p = 0.5, shape = a, rate = b) # median\npostmode <- (a-1)/b # mode\ncredint <- qgamma(p = c(alpha/2, 1-alpha/2), shape = a, rate = b)\n# Documentation states you must return the quantile function\nHDInterval::hdi(\n    object = qgamma, \n    shape = a, \n    rate = b, \n    credMass = 0.50)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    lower     upper \n0.1042228 0.1589696 \nattr(,\"credMass\")\n[1] 0.5\n```\n:::\n\n```{.r .cell-code}\n# Alternatively, find this numerically\n# MAP via minimization of the negative log likelihood\nMAP <- optimize(\n  f = function(x){-dgamma(x, shape = a, rate = b, log = TRUE)},\n  interval = qgamma(p = c(0.2,0.8), shape = a, rate = b)\n  )$minimum\n# Other quantities approximated by Monte Carlo\n# Sample from posterior\npost_samp <- rgamma(n = 1e4, shape = a, rate = b)\n# Sample mean and sample quantiles\nmean(post_samp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1422132\n```\n:::\n\n```{.r .cell-code}\nquantile(post_samp, c(alpha/2, 0.5, 1-alpha/2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      5.5%        50%      94.5% \n0.08286817 0.13834515 0.21530067 \n```\n:::\n\n```{.r .cell-code}\n# Highest posterior density interval\ncredHDI <- HDInterval::hdi(\n  object = post_samp, \n  credMass = 0.50)\ncredHDI\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    lower     upper \n0.1061453 0.1597930 \nattr(,\"credMass\")\n[1] 0.5\n```\n:::\n:::\n\n\nUp to three significant digits, the posterior mean is 0.142, the median is 0.138 and the mode 0.13. The bounds of the equitailed 89% credible interval are [0.082, 0.215], those of the 50% HDPI [0.1061453, 0.159793].\n\nFor the posterior predictive, we simply take the samples from the posterior, `post_samp`, and generate for each rate a new exponential\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\npostpred_samp <- rexp(n = 1000, rate = post_samp[seq_len(1000)])\nggplot(data = data.frame(x = postpred_samp))+\n  geom_histogram(aes(x = x, y = ..density..)) + \n  # the likelihood is proportional to a gamma\n  stat_function(fun = dexp,  \n                n = 1001, \n                args = list(rate = 1/8) # mle is average\n                ) +\n  labs(x = \"waiting time (in minutes)\", \n       y = \"\") +\n  scale_x_continuous(limits = c(0, NA), expand = expansion(mult = c(0, .1))) +\n  scale_y_continuous(limits = c(0, NA), expand = expansion(mult = c(0, .1))) +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![Histogram of posterior predictive draws and density function of observations.](01-solution_files/figure-html/fig-postpred-exp-1.png){#fig-postpred-exp width=672}\n:::\n:::\n\n\n\n:::\n",
    "supporting": [
      "01-solution_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}